import React, { createContext, useContext, useState, useEffect } from 'react';

const translations = {
  en: {
    // Navigation
    nav: {
      home: 'Home',
      marketplace: 'Marketplace',
      portfolio: 'My Portfolio',
      booking: 'Book Hotel',
      governance: 'DAO Governance',
      esgRewards: 'ESG Rewards',
      staking: 'DRA Staking',
      login: 'Login',
      register: 'Register',
      logout: 'Logout',
      user: 'User',
    },

    // Register and login
   authRegister: {
    createAccount: "Create Account",
    joinInvestment: "Join us to start your investment journey",
    register: "Register",
    firstName: "First Name",
    lastName: "Last Name",
    firstNamePlaceholder:'john',
    lastNamePlaceholder:'Doe',
    email: "Email Address",
    password: "Password",
    confirmPassword: "Confirm Password",
    passwordPlaceholder: "At least 8 characters",
    confirmPasswordPlaceholder: "Re-enter your password",
    agreeTerms: "I agree to the",
    termsConditions: "Terms & Conditions",
    haveAlradyCount:'Already have an account',
    loginHere:'login here',
    createBtn: "Create Account"
    
  },
  authLogin: {
      welcomeBack: "Welcome Back",
      loginToAccess: "Login to access your investment portfolio",
      email: "Email Address",
      password: "Password",
      passwordPlaceholder: "Enter your password",
      rememberMe: "Remember me",
      forgotPassword: "Forgot password?",
      loginBtn: "Login",
      dontHaveAccount: "Don't have an account?",
      registerNow: "Register now"
    },

    // Home Page
    home: {
      badge: "Hong Kong's First Hotel RWA Tokenization Platform",
      title1: 'Invest in Premium Hotels',
      title2: 'Starting from $1',
      subtitle: 'DIGIREAL ASSETS tokenizes hotel assets, enabling easy participation in premium hotel investments with stable rental yields and asset appreciation.',
      exploreBtn: 'Explore Hotel Assets',
      learnMore: 'Learn More',
      features: {
        lowEntry: { title: 'Low Entry', desc: 'Start investing from $1, accessible to everyone' },
        stableYield: { title: 'Stable Yield', desc: '6-10% APY backed by real hotel revenue' },
        hkCompliant: { title: 'HK Compliant', desc: 'Aligned with SFC A-S-P-I-Re framework' },
        globalLiquidity: { title: 'Global Liquidity', desc: 'Base chain tokenization, trade anytime' },
      },
      hotHotels: 'Hot Hotel Assets',
      viewAll: 'View All',
      quickActions: 'Quick Actions',
      bookRoom: '🏨 Book Hotel Room',
      joinDao: '🗳️ Join DAO Governance',
      esgRewards: '🌿 ESG Energy Rewards',
      stakeDra: '💎 Stake DRA Tokens',
    },
    // Stats
    stats: {
      tvl: 'Total Value Locked (TVL)',
      tokenizedHotels: 'Tokenized Hotels',
      avgApy: 'Average APY',
      activeInvestors: 'Active Investors',
    },
    // Hotel Card
    hotelCard: {
      upcoming: 'Upcoming',
      active: 'Fundraising',
      soldOut: 'Sold Out',
      tokenPrice: 'Token Price',
      apy: 'APY',
      progress: 'Progress',
      tokens: 'tokens',
      viewDetails: 'View Details',
    },
    // Portfolio
    portfolio: {
      title: 'My Portfolio',
      subtitle: 'Manage your hotel token investments and yields',
      totalInvested: 'Total Invested',
      totalEarned: 'Total Earned',
      pendingRewards: 'Pending Rewards',
      stakedTokens: 'Staked Tokens',
      activeInvestments: 'Active Investments',
      staking: 'Staking',
      noInvestments: 'No Investments Yet',
      startInvesting: 'Start investing in tokenized hotel assets for stable returns',
      browseAssets: 'Browse Hotel Assets',
      claim: 'Claim',
      details: 'Details',
      holdingTokens: 'Holding Tokens',
      loginRequired: 'Please Login',
      loginToView: 'Login to view your portfolio',
    },
    // Marketplace
    marketplace: {
      title: 'Hotel Asset Marketplace',
      subtitle: 'Explore premium tokenized hotel assets worldwide',
      searchPlaceholder: 'Search hotel name, location...',
      allStatus: 'All Status',
      fundraising: 'Fundraising',
      upcoming: 'Upcoming',
      soldOut: 'Sold Out',
      newest: 'Newest',
      highestApy: 'Highest APY',
      priceLowHigh: 'Price: Low to High',
      priceHighLow: 'Price: High to Low',
      noResults: 'No matching hotel assets found',
      adjustFilters: 'Try adjusting your filters',
    },
    // Hotel Detail
    hotelDetail: {
      back: 'Back',
      tokenPrice: 'Token Price',
      apy: 'APY',
      totalValue: 'Total Value',
      totalTokens: 'Total Tokens',
      progress: 'Progress',
      remaining: 'remaining tokens available',
      investNow: 'Invest Now',
      bookStay: '🏨 Book a Stay',
      overview: 'Asset Overview',
      performance: 'Performance',
      documents: 'Documents',
      rooms: 'Rooms',
      occupancy: 'Occupancy',
      revpar: 'RevPAR',
      leaseEnd: 'Lease End',
      quarterlyReturns: 'Historical Quarterly Returns',
      assetReport: 'Asset Valuation Report',
      leaseSummary: 'Lease Contract Summary',
      auditReport: 'Audit Report',
      contractAddress: 'Token Contract Address',
      investIn: 'Invest in',
      investAmount: 'Investment Amount (USDC)',
      tokensReceive: 'Tokens to Receive',
      expectedYield: 'Expected Annual Yield',
      confirmInvest: 'Confirm Investment',
      processing: 'Processing...',
      pleaseLogin: 'Please Login',
      investSuccess: 'Investment Successful!',
      purchased: 'You have successfully purchased',
    },
    // Booking
    booking: {
      title: 'Hotel Booking',
      subtitle: 'Book with USDC or DRA tokens, token holders get exclusive discounts',
      selectHotel: 'Select Hotel',
      selectHotelPlaceholder: 'Select a hotel',
      stayInfo: 'Stay Information',
      checkIn: 'Check-in Date',
      checkOut: 'Check-out Date',
      selectDate: 'Select date',
      roomType: 'Room Type',
      standard: 'Standard Room',
      deluxe: 'Deluxe Room',
      suite: 'Suite',
      perNight: '/night',
      guests: 'Guests',
      person: 'person',
      people: 'people',
      paymentMethod: 'Payment Method',
      stablecoin: 'Stablecoin Payment',
      hotelToken: 'Hotel Asset Token',
      draDiscount: '5% Discount',
      orderSummary: 'Order Summary',
      nights: 'nights',
      tokenHolderDiscount: 'Token Holder Discount (15%)',
      draPaymentDiscount: 'DRA Payment Discount (5%)',
      total: 'Total',
      confirmBooking: 'Confirm Booking',
      selectHotelAndDates: 'Please select hotel and dates',
      tokenHolderPerk: "You're a token holder, enjoy 15% exclusive discount",
      bookingSuccess: 'Booking Successful!',
      confirmationCode: 'Your Confirmation Code',
      hotel: 'Hotel',
      bookNow:'Book Now',
      continueBooking: 'Continue Booking',
      holderExclusive: 'Holder Exclusive',
    },
    // Governance
    governance: {
      title: 'DAO Governance',
      subtitle: 'Participate in platform decisions, your DRA tokens are your voting power',
      createProposal: 'Create Proposal',
      activeProposals: 'Active Proposals',
      passed: 'Passed',
      totalVotingPower: 'Total Voting Power',
      participants: 'Participants',
      proposalTitle: 'Proposal Title',
      proposalCategory: 'Proposal Category',
      proposalDescription: 'Proposal Description',
      descriptionPlaceholder: 'Describe your proposal in detail...',
      submitProposal: 'Submit Proposal',
      submitting: 'Submitting...',
      categories: {
        asset_acquisition: 'Asset Acquisition',
        fee_adjustment: 'Fee Adjustment',
        partnership: 'Partnership',
        platform_upgrade: 'Platform Upgrade',
        esg_initiative: 'ESG Initiative',
      },
      status: {
        active: 'Voting',
        passed: 'Passed',
        rejected: 'Rejected',
        executed: 'Executed',
      },
      voteFor: 'For',
      voteAgainst: 'Against',
      totalVotes: 'Total Votes',
      quorum: 'quorum',
      remaining: 'remaining',
      votingEnded: 'Voting ended',
      noProposals: 'No Proposals Yet',
      beFirst: 'Be the first to create a proposal',
    },
    // ESG Rewards
    esg: {
      title: 'ESG Energy Rewards',
      subtitle: 'Earn rewards for eco-friendly actions, verified by IoT sensors',
      totalRewards: 'Total Rewards',
      pending: 'Pending',
      actions: 'Eco Actions',
      carbonReduced: 'Carbon Reduced',
      rewardableActions: 'Rewardable Actions',
      acOff: 'Turn Off AC',
      towelReuse: 'Towel Reuse',
      noCleaning: 'Skip Room Cleaning',
      waterSaving: 'Water Saving',
      recycling: 'Recycling',
      howToEarn: 'How to Earn Rewards?',
      step1: 'Stay at a tokenized partner hotel',
      step2: 'Take eco-friendly actions',
      step3: 'IoT sensors verify automatically',
      step4: 'Instant payment via x402 protocol',
      rewardHistory: 'Reward History',
      claimAll: 'Claim All',
      loginToView: 'Please login to view your reward history',
      noRewards: 'No Reward History',
      stayToEarn: 'Stay at partner hotels and take eco-friendly actions to earn rewards',
      claim: 'Claim',
      status: {
        pending: 'Verifying',
        verified: 'Claimable',
        claimed: 'Claimed',
      },
      impact: 'Your Environmental Impact',
      waterSaved: 'Water Saved (L)',
      energySaved: 'Energy Saved (kWh)',
      carbonReduction: 'Carbon Reduction (kg)',
    },
    // Staking
    staking: {
      title: 'DRA Token Staking',
      subtitle: 'Stake DRA tokens to earn rewards and boost your voting power',
      totalStaked: 'Total Staked',
      totalRewards: 'Total Rewards',
      avgApy: 'Average APY',
      votingPower: 'Voting Power',
      stakeDra: 'Stake DRA',
      unstake: 'Unstake',
      claimRewards: 'Claim Rewards',
      stakeAmount: 'Stake Amount',
      available: 'Available',
      lockPeriod: 'Lock Period',
      days: 'days',
      expectedRewards: 'Expected Rewards',
      votingBoost: 'Voting Power Boost',
      confirmStake: 'Confirm Stake',
      stakeSuccess: 'Staking Successful!',
      youStaked: 'You have staked',
      activeStakes: 'Active Stakes',
      stakingHistory: 'Staking History',
      noStakes: 'No Active Stakes',
      startStaking: 'Start staking to earn rewards and boost voting power',
      unlockDate: 'Unlock Date',
      pendingRewards: 'Pending Rewards',
      earned: 'Earned',
      status: {
        active: 'Staking',
        unstaking: 'Unstaking',
        completed: 'Completed',
      },
      lockPeriods: {
        30: '30 Days - 8% APY',
        90: '90 Days - 12% APY',
        180: '180 Days - 18% APY',
        365: '365 Days - 25% APY',
      },
      multipliers: {
        30: '1.2x',
        90: '1.5x',
        180: '2x',
        365: '3x',
      },
      locked: 'Locked',
      unlocked: 'Unlocked',
      daysLeft: 'days left',
      earlyUnstakeFee: 'Early unstake fee: 10%',
      max: 'MAX',
    },
    // Common
    common: {
      draBalance: 'DRA Balance',
      votingPower: 'Voting Power',
      pendingRewards: 'Pending Rewards',
      myPortfolio: 'My Portfolio',
      noData: 'No Data',
      loading: 'Loading...',
      error: 'Error',
      success: 'Success',
      cancel: 'Cancel',
      confirm: 'Confirm',
      save: 'Save',
      edit: 'Edit',
      delete: 'Delete',
      search: 'Search',
      filter: 'Filter',
      sort: 'Sort',
      all: 'All',
      login: 'Login',
    },
    // register and login

    
    // Footer
    footer: {
      copyright: '© 2025 DIGIREAL ASSETS. Hong Kong Regulated.',
      baseChain: 'Base Chain',
      sfcCompliant: 'SFC Compliant',
      x402Protocol: 'x402 Protocol',
    },
  },
  zh: {
    // Navigation
    nav: {
      home: '首页',
      marketplace: '资产市场',
      portfolio: '我的投资',
      booking: '预订酒店',
      governance: 'DAO治理',
      esgRewards: 'ESG奖励',
      staking: 'DRA质押',
      login: '登录',
      register:'注册',
      logout: '退出登录',
      user: '用户',
    },
     authRegister: {
      createAccount: "创建账户",
      joinInvestment: "加入我们开始您的投资之旅",
      register: "注册",
      firstName: "名",
      lastName: "姓",
    firstNamePlaceholder:'名',
    lastNamePlaceholder:'姓',
      email: "电子邮件地址",
      password: "密码",
      confirmPassword: "确认密码",
      passwordPlaceholder: "至少 8 个字符",
      confirmPasswordPlaceholder: "再次输入密码",
      agreeTerms: "我同意",
      termsConditions: "条款和条件",
      haveAlradyCount:'已经有账户了吗？',
      loginHere:'点击登录',
      createBtn: "创建账户",
      
    },

     authLogin: {
      welcomeBack: "欢迎回来",
      loginToAccess: "登录以访问您的投资组合",
      email: "电子邮件地址",
      password: "密码",
      passwordPlaceholder: "请输入密码",
      rememberMe: "记住我",
      forgotPassword: "忘记密码？",
      loginBtn: "登录",
      dontHaveAccount: "没有账户？",
      registerNow: "立即注册"
    },
    // Home Page
    home: {
      badge: '香港首个酒店RWA代币化平台',
      title1: '投资全球优质酒店',
      title2: '从$1开始',
      subtitle: 'DIGIREAL ASSETS将酒店资产代币化，让您轻松参与高端酒店投资，享受稳定租金收益和资产增值。',
      exploreBtn: '探索酒店资产',
      learnMore: '了解更多',
      features: {
        lowEntry: { title: '低门槛投资', desc: '最低$1起投，人人可参与优质酒店资产' },
        stableYield: { title: '稳定收益', desc: '6-10% APY，基于真实酒店租金收入' },
        hkCompliant: { title: '香港合规', desc: '符合SFC A-S-P-I-Re监管框架' },
        globalLiquidity: { title: '全球流通', desc: 'Base链代币化，随时买卖无锁定' },
      },
      hotHotels: '热门酒店资产',
      viewAll: '查看全部',
      quickActions: '快速操作',
      bookRoom: '🏨 预订酒店房间',
      joinDao: '🗳️ 参与DAO治理',
      esgRewards: '🌿 ESG节能奖励',
      stakeDra: '💎 质押DRA代币',
    },
    // Stats
    stats: {
      tvl: '总锁仓价值 (TVL)',
      tokenizedHotels: '代币化酒店',
      avgApy: '平均年化收益',
      activeInvestors: '活跃投资者',
    },
    // Hotel Card
    hotelCard: {
      upcoming: '即将上线',
      active: '募集中',
      soldOut: '已售罄',
      tokenPrice: '代币价格',
      apy: '年化收益',
      progress: '募集进度',
      tokens: '代币',
      viewDetails: '查看详情',
    },
    // Portfolio
    portfolio: {
      title: '我的投资组合',
      subtitle: '管理您的酒店代币投资和收益',
      totalInvested: '总投资额',
      totalEarned: '累计收益',
      pendingRewards: '待领取收益',
      stakedTokens: '已质押代币',
      activeInvestments: '活跃投资',
      staking: '质押中',
      noInvestments: '暂无投资',
      startInvesting: '开始投资代币化酒店资产，享受稳定收益',
      browseAssets: '浏览酒店资产',
      claim: '领取',
      details: '详情',
      holdingTokens: '持有代币',
      loginRequired: '请先登录',
      loginToView: '登录后查看您的投资组合',
    },
    // Marketplace
    marketplace: {
      title: '酒店资产市场',
      subtitle: '探索全球优质代币化酒店资产，开始您的投资之旅',
      searchPlaceholder: '搜索酒店名称、地区...',
      allStatus: '全部状态',
      fundraising: '募集中',
      upcoming: '即将上线',
      soldOut: '已售罄',
      newest: '最新上架',
      highestApy: '收益最高',
      priceLowHigh: '价格从低到高',
      priceHighLow: '价格从高到低',
      noResults: '未找到匹配的酒店资产',
      adjustFilters: '请尝试调整筛选条件',
    },
    // Hotel Detail
    hotelDetail: {
      back: '返回',
      tokenPrice: '代币价格',
      apy: '年化收益率',
      totalValue: '资产总价值',
      totalTokens: '代币总量',
      progress: '募集进度',
      remaining: '代币可购',
      investNow: '立即投资',
      bookStay: '🏨 预订入住',
      overview: '资产概览',
      performance: '收益表现',
      documents: '相关文档',
      rooms: '房间数量',
      occupancy: '入住率',
      revpar: 'RevPAR',
      leaseEnd: '租赁到期',
      quarterlyReturns: '历史收益表现',
      assetReport: '资产评估报告',
      leaseSummary: '租赁合同摘要',
      auditReport: '审计报告',
      contractAddress: '代币合约地址',
      investIn: '投资',
      investAmount: '投资金额 (USDC)',
      tokensReceive: '获得代币',
      expectedYield: '预期年收益',
      confirmInvest: '确认投资',
      processing: '处理中...',
      pleaseLogin: '请先登录',
      investSuccess: '投资成功!',
      purchased: '您已成功购买',
    },
    // Booking
    booking: {
      title: '酒店预订',
      subtitle: '使用USDC或DRA代币预订合作酒店，代币持有者享专属折扣',
      selectHotel: '选择酒店',
      selectHotelPlaceholder: '选择酒店',
      stayInfo: '入住信息',
      checkIn: '入住日期',
      checkOut: '离店日期',
      selectDate: '选择日期',
      roomType: '房型',
      standard: '标准房',
      deluxe: '豪华房',
      suite: '套房',
      perNight: '/晚',
      guests: '入住人数',
      person: '人',
      people: '人',
      paymentMethod: '支付方式',
      stablecoin: '稳定币支付',
      hotelToken: '酒店资产代币',
      draDiscount: '5%折扣',
      orderSummary: '订单摘要',
      nights: '晚',
      tokenHolderDiscount: '代币持有者折扣 (15%)',
      draPaymentDiscount: 'DRA支付折扣 (5%)',
      total: '总计',
      confirmBooking: '确认预订',
      selectHotelAndDates: '请选择酒店和入住日期',
      tokenHolderPerk: '您是代币持有者，享受15%专属折扣',
      bookingSuccess: '预订成功!',
      confirmationCode: '您的预订确认码',
      hotel: '酒店',
      continueBooking: '继续预订',
      holderExclusive: '持有者专属',
    },
    // Governance
    governance: {
      title: 'DAO治理',
      subtitle: '参与平台决策，您的DRA代币即您的投票权',
      createProposal: '发起提案',
      activeProposals: '活跃提案',
      passed: '已通过',
      totalVotingPower: '总投票权',
      participants: '参与人数',
      proposalTitle: '提案标题',
      proposalCategory: '提案类别',
      proposalDescription: '提案描述',
      descriptionPlaceholder: '详细描述您的提案...',
      submitProposal: '提交提案',
      submitting: '提交中...',
      categories: {
        asset_acquisition: '资产收购',
        fee_adjustment: '费用调整',
        partnership: '合作伙伴',
        platform_upgrade: '平台升级',
        esg_initiative: 'ESG倡议',
      },
      status: {
        active: '投票中',
        passed: '已通过',
        rejected: '已否决',
        executed: '已执行',
      },
      voteFor: '赞成',
      voteAgainst: '反对',
      totalVotes: '总投票',
      quorum: '法定人数',
      remaining: '剩余',
      votingEnded: '投票已结束',
      noProposals: '暂无提案',
      beFirst: '成为第一个发起提案的人',
    },
    // ESG Rewards
    esg: {
      title: 'ESG节能奖励',
      subtitle: '通过节能环保行为赚取奖励，每个行动都经IoT传感器验证',
      totalRewards: '累计奖励',
      pending: '待领取',
      actions: '节能行为',
      carbonReduced: '碳减排',
      rewardableActions: '可获奖励的行为',
      acOff: '关闭空调',
      towelReuse: '毛巾重复使用',
      noCleaning: '跳过客房清洁',
      waterSaving: '节水行为',
      recycling: '垃圾分类',
      howToEarn: '如何获得奖励?',
      step1: '入住代币化合作酒店',
      step2: '执行节能环保行为',
      step3: 'IoT传感器自动验证',
      step4: '通过x402协议即时到账',
      rewardHistory: '奖励记录',
      claimAll: '领取全部',
      loginToView: '请登录查看您的奖励记录',
      noRewards: '暂无奖励记录',
      stayToEarn: '入住合作酒店并执行节能行为即可获得奖励',
      claim: '领取',
      status: {
        pending: '验证中',
        verified: '可领取',
        claimed: '已领取',
      },
      impact: '您的环保贡献',
      waterSaved: '节约用水(升)',
      energySaved: '节约电力(kWh)',
      carbonReduction: '减少碳排放(kg)',
    },
    // Staking
    staking: {
      title: 'DRA代币质押',
      subtitle: '质押DRA代币赚取收益，提升投票权',
      totalStaked: '总质押量',
      totalRewards: '累计奖励',
      avgApy: '平均年化',
      votingPower: '投票权',
      stakeDra: '质押DRA',
      unstake: '解除质押',
      claimRewards: '领取奖励',
      stakeAmount: '质押数量',
      available: '可用余额',
      lockPeriod: '锁定期',
      days: '天',
      expectedRewards: '预期收益',
      votingBoost: '投票权加成',
      confirmStake: '确认质押',
      stakeSuccess: '质押成功!',
      youStaked: '您已成功质押',
      activeStakes: '活跃质押',
      stakingHistory: '质押记录',
      noStakes: '暂无质押',
      startStaking: '开始质押以赚取收益并提升投票权',
      unlockDate: '解锁日期',
      pendingRewards: '待领取奖励',
      earned: '已获得',
      status: {
        active: '质押中',
        unstaking: '解除中',
        completed: '已完成',
      },
      lockPeriods: {
        30: '30天 - 8% 年化',
        90: '90天 - 12% 年化',
        180: '180天 - 18% 年化',
        365: '365天 - 25% 年化',
      },
      multipliers: {
        30: '1.2倍',
        90: '1.5倍',
        180: '2倍',
        365: '3倍',
      },
      locked: '锁定中',
      unlocked: '已解锁',
      daysLeft: '天后解锁',
      earlyUnstakeFee: '提前解除手续费: 10%',
      max: '最大',
    },
    // Common
    common: {
      draBalance: 'DRA余额',
      votingPower: '投票权',
      pendingRewards: '待领取收益',
      myPortfolio: '我的投资组合',
      noData: '暂无数据',
      loading: '加载中...',
      error: '错误',
      success: '成功',
      cancel: '取消',
      confirm: '确认',
      save: '保存',
      edit: '编辑',
      delete: '删除',
      search: '搜索',
      filter: '筛选',
      sort: '排序',
      all: '全部',
      login: '登录',
      register:'注册',
    },
    // Footer
    footer: {
      copyright: '© 2025 DIGIREAL ASSETS. 香港合规运营.',
      baseChain: 'Base链',
      sfcCompliant: 'SFC合规',
      x402Protocol: 'x402协议',
    },
  }
};

// @ts-ignore
const LanguageContext = createContext();

export function LanguageProvider({ children }) {
  const [language, setLanguage] = useState(() => {
    if (typeof window !== 'undefined') {
      return localStorage.getItem('language') || 'zh';
    }
    return 'zh';
  });

  useEffect(() => {
    localStorage.setItem('language', language);
  }, [language]);

  const t = (key) => {
    const keys = key.split('.');
    let value = translations[language];
    for (const k of keys) {
      value = value?.[k];
    }
    return value || key;
  };

  const toggleLanguage = () => {
    setLanguage(prev => prev === 'zh' ? 'en' : 'zh');
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, toggleLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}